--1. Create Schema
CREATE SCHEMA `NISUM` DEFAULT CHARACTER SET utf8 ;

--2. Create Tables
CREATE TABLE `NISUM`.`COUNTRIES` (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `NISUM`.`CITIES` (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE `NISUM`.`USERS` (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(250) NOT NULL,
	TOKEN VARCHAR(250),
	IS_ACTIVE BOOLEAN DEFAULT FALSE NOT NULL,
	LAST_LOGIN DATE,
	CREATED DATE DEFAULT CURRENT_DATE NOT NULL,
	MODIFIED DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT USERS_UN UNIQUE (EMAIL)
);

CREATE TABLE `NISUM`.`PHONES` (
    ID INT NOT NULL AUTO_INCREMENT,
	ID_USER UUID NOT NULL,
	PHONE_NUMBER VARCHAR(100) NOT NULL,
	CITY_CODE INT NOT NULL,
	COUNTRY_CODE INT NOT NULL,
    CONSTRAINT ID PRIMARY KEY (ID),
	CONSTRAINT FK_PHONE_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
	FOREIGN KEY (COUNTRY_CODE) REFERENCES COUNTRIES(ID),
	FOREIGN KEY (CITY_CODE) REFERENCES CITIES(ID),
	CONSTRAINT PHONES_UN UNIQUE (ID_USER, PHONE_NUMBER, CITY_CODE, COUNTRY_CODE)
);

--3. INSERTS
INSERT INTO `NISUM`.`COUNTRIES` (ID, NAME) VALUES (1, 'ARGENTINA');
INSERT INTO `NISUM`.`COUNTRIES` (ID, NAME) VALUES (2, 'BRASIL');
INSERT INTO `NISUM`.`COUNTRIES` (ID, NAME) VALUES (3, 'CHILE');

INSERT INTO `NISUM`.`CITIES` (ID, NAME) VALUES (1, 'Buenos Aires');
INSERT INTO `NISUM`.`CITIES` (ID, NAME) VALUES (2, 'Rio de Janeiro');
INSERT INTO `NISUM`.`CITIES` (ID, NAME) VALUES (3, 'Santiago de Chile');
